[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false

[logger]
level = "info"

[style]
buttonColor = "#4CAF50"
buttonTextColor = "#FFFFFF"
inputBackgroundColor = "#E0E0E0"
inputTextColor = "#000000"
headerColor = "#333333"
headerTextColor = "#FFFFFF"